channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - imbalanced-learn==0.11.0
  - lightgbm==3.3.5
  - matplotlib==3.8.0
  - numpy==1.23.5
  - packaging==23.1
  - pandas==2.0.2
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.1
name: mlflow-env
