# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - medlionp7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://medlionp7.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_95ae55a574184aa7a55f221b24f69adf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb7d37b998694ff89bfb4fad4d647a64 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: medlionp7.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_95ae55a574184aa7a55f221b24f69adf }}/mon_image_medp7:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'medlionp7'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_916824fc3d27494fae74584c8a3cc1ab }}
        images: 'medlionp7.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_95ae55a574184aa7a55f221b24f69adf }}/mon_image_medp7:${{ github.sha }}'
